name: Hourly script runner

# grant the token write access so it can push
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Configure git
        run: |
          # git config user.name "github-actions[bot]"
          # git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "Yechiel Worenklein"
          git config user.email "41305372+yechielw@users.noreply.github.com"

      - name: Run script
        run: |
          bash ./update.sh

      - name: Commit & push if changed
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            VERSION=$(jq -r '.[0].Version' latest.json)
            git commit -m "Automated update to version $VERSION"

            if git rev-parse -q --verify "refs/tags/$VERSION" >/dev/null; then
              echo "Tag $VERSION already exists; skipping tag creation."
            else
              git tag "$VERSION"
            fi
          fi
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.PUSHPAT }}
          tags: true
